### PR TITLE
Add Sphinx-based documentation

### PR DESCRIPTION
**Pull request by domgz**
The aim of this PR is to enhance the existing README file and to include a simple Sphinx-based documentation that explains the usage in greater detail.

The main motivation behind the enhancement is the inclusion of a [simulation inputs](https://simnanodome.readthedocs.io/en/documentation/usage.html#simulation-inputs) section featuring a diagram of the CUDS that have to be created to serve as inputs for the sessions. This section should be further enhanced and turned into a "simulation inputs and outcomes" session that also shows the outputs of the simulation in the diagram (e.g. in a different color), or alternatively, the outputs for each operation mode should be depicted in their own diagram in each operation mode subsection.

### CODE REVIEW

**Comment by domgz** [comment]
@giorgiolacivita I tried to make this task as easy as possible by doing much of the hard work for you. You can preview the documentation from this PR [here](https://simnanodome.readthedocs.io/en/documentation/). Every time you push to this branch, the documentation is rebuilt after a few minutes. You may need to refresh the page with ctrl+f5 to see the changes sometimes (ignores the browser's cache).

Please have a look at the documentation an correct it as you see fit, as I am very sure that I got many things wrong. The diagram show on the [usage section](https://simnanodome.readthedocs.io/en/documentation/usage.html#simulation-inputs) is [here](https://github.com/simphony/SimNanoDOME/blob/documentation/docs/static/graph_pattern.drawio.svg). It has been created, and can be edited with [diagrams.net](https://app.diagrams.net/). Please make sure it is factually correct and make any changes that are needed. The **simulation outputs are missing** (I am talking about the `NanoParticleSizeDistribution`, `TemperatureStreamLine`, `ParticleDiameter`, `ParticleNumberDensity`, `ParticleVolumePercentage`, `Bin`, `ParticleFractalDimension`, etc) modify the diagram to include them, or if they are very different for the various operation modes, think of a way to make a separate diagram for each one that is still understandable.

**Comment by domgz** [comment]
@giorgiolacivita Please take care also of this point (putting the output CUDS patterns in the diagrams) before we merge this to master. You can modify the diagrams in the same way that it was done for the [SimCMLCKinetics wrapper](https://simcmclkinetics.readthedocs.io/en/documentation/usage.html).

> The diagram show on the [usage section](https://simnanodome.readthedocs.io/en/documentation/usage.html#simulation-inputs) is [here](https://github.com/simphony/SimNanoDOME/blob/documentation/docs/static/graph_pattern.drawio.svg). It has been created, and can be edited with [diagrams.net](https://app.diagrams.net/). Please make sure it is factually correct and make any changes that are needed. The **simulation outputs are missing** (I am talking about the `NanoParticleSizeDistribution`, `TemperatureStreamLine`, `ParticleDiameter`, `ParticleNumberDensity`, `ParticleVolumePercentage`, `Bin`, `ParticleFractalDimension`, etc) modify the diagram to include them, or if they are very different for the various operation modes, think of a way to make a separate diagram for each one that is still understandable.

**Comment by giorgiolacivita** [comment]
@kysrpex i think it should be ok now. Let me know if you think i should add some more content.

**Comment by domgz** [comment]
> @kysrpex i think it should be ok now. Let me know if you think i should add some more content.

I checked your modifications but unfortunately this is not what was meant by "putting the output CUDS patterns in the diagrams". Please compare the [previous diagram](https://github.com/simphony/SimNanoDOME/blob/89dbea2b7d013d71a0943d4f9ec25d6189191677/docs/static/nanodome.drawio.svg) with the new one that I have uploaded, hopefully this makes the point clear. As I proposed to do it in same way that it was done for the [SimCMLCKinetics wrapper](https://simcmclkinetics.readthedocs.io/en/documentation/usage.html), I also took the chance to use the same color schema and put the inputs and outputs in different sections.

At this point it is up to you to either put the outputs in the remaining diagrams and use a unified color schema, or just revert to commit [89dbea2](https://github.com/simphony/SimNanoDOME/pull/5/commits/89dbea2b7d013d71a0943d4f9ec25d6189191677) and deliver things as they were in such commit. Just let me know when I can click the merge button.

**Comment by giorgiolacivita** [comment]
@kysrpex i followed your suggestions and reviewed the docs. You can merge now.

**Comment by domgz** [comment]
> @kysrpex i followed your suggestions and reviewed the docs. You can merge now.

Thank you very much Giorgio. I see in the changes that you made that now there is no misunderstanding. I am not thoroughly checking the outputs, as I assume there are no mistakes. I am merging the PR now.

**Pull request merged**
